# Generated by Django 5.2.6 on 2025-09-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishers',
            new_name='publisher',
        ),
    ]
