# Generated by Django 5.2.6 on 2025-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_rename_publishers_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='given_back',
            field=models.BooleanField(default=False),
        ),
    ]
