# Generated by Django 5.2.6 on 2025-09-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_lending_given_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='given_back',
        ),
    ]
