# Generated by Django 5.2.6 on 2025-09-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_remove_lending_given_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
